name: EquivalencyTech
version: 1.0.1
main: io.github.sefiraat.equivalencytech.EquivalencyTech
api-version: 1.16
softdepend:
  - Slimefun
permissions:
  equivalencytech.admin:
    description: Allows access to /et