name: Java CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0
      - name: Set up JDK 8
        uses: actions/setup-java@v2.5.0
        with:
          java-version: 8
          distribution: adopt
      - name: Build with Maven
        run: mvn package --file pom.xml
        
      - name: Upload to repo
        uses: actions/upload-artifact@v2
        with:
          name: workspace
          path: ${{ github.workspace }}
